[build]
  base = "examples/docs/"
  publish = "dist/"
  command = "export ELM_HOME=\"$NETLIFY_CACHE_DIR/elm\" && cd ../../ && npm run build && cd examples/docs && npm install && npm run build"
  ignore = "git diff --quiet HEAD^ HEAD `git rev-parse --show-toplevel`"
